version: "3.5"

services:

  db:
    image: mongo:4.4.10
    container_name: db
    restart: always
    ports:
      - "${MONGO_PORT}:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - ./db:/data/db

  app:
    image: eurekabpo/esb:${ESB_VERSION}-mongodb
    ports:
      - "8080:8080"
    restart: always
    extra_hosts:
      host.docker.internal: host-gateway
    environment:
      MONGO_SERVERS: host.docker.internal
      MONGO_DATABASE: ${MONGO_DB_NAME}
      MONGO_USER: ${MONGO_USER}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - ./app/configuration.yaml:/opt/esb-app/configuration.yaml
    depends_on:
      - db
